name: Phirepass daemon
description: Phirepass daemon addon for Home Assistant
version: 1.0.10-85
slug: phirepass-daemon-ha
arch:
  - aarch64
  - amd64
startup: services
panel_icon: mdi:console
panel_title: Phirepass
schema:
    APP_MODE: match(dev|development|prod|production)?
    HOST: str?
    PORT: int?
    SERVER_HOST: str?
    SERVER_PORT: int?
    SSH_HOST: str?
    SSH_PORT: int?
    SSH_AUTH_METHOD: match(password|none)?
options:
    APP_MODE: production
    HOST: 0.0.0.0
    PORT: 18080
    SERVER_HOST: phirepass.local
    SERVER_PORT: 8080
    SSH_HOST: 0.0.0.0
    SSH_PORT: 22
    SSH_AUTH_METHOD: none
required:
    - HOST
    - PORT
    - SERVER_HOST
    - SERVER_PORT
    - SSH_HOST
    - SSH_PORT
#hassio_api: true
#hassio_role: manager
#homeassistant_api: true
#host_network: true
#uart: true
#usb: true
#gpio: true
#audio: true
#apparmor: false
#host_dbus: true
#docker_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
  - config:rw
#tmpfs: true
#journald: true
