name: Phirepass daemon
description: Phirepass daemon addon for Home Assistant
version: 1.0.10-2
slug: phirepass-daemon-ha
arch:
  - aarch64
  - amd64
startup: application
boot: auto
schema:
    APP_MODE:
      select:
        - development
        - production
    HOST: str?
    PORT: int?
    SERVER_HOST: str?
    SERVER_PORT: int?
    SSH_HOST: str?
    SSH_PORT: int?
options:
    APP_MODE: production
    HOST: 0.0.0.0
    PORT: 18080
    SERVER_HOST: phirepass.local
    SERVER_PORT: 8080
    SSH_HOST: 0.0.0.0
    SSH_PORT: 22
required:
    - HOST
    - PORT
    - SERVER_HOST
    - SERVER_PORT
    - SSH_HOST
    - SSH_PORT
host_network: true
host_dbus: true
tmpfs: true
