name: Phirepass daemon
description: Phirepass daemon addon for Home Assistant
version: 1.0.0
slug: phirepass-daemon-ha
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
    8080/tcp: 8080
ports_description:
    8080/tcp: Web interface
environment:
    PORT: "{{ options.port }}"
schema:
    port: int?
options:
    port: 8080
required:
    - port
homeassistant_api: true
privileged: []
full_access: []
devices: []
realms:
    - api
host_network: true
host_dbus: true
tmpfs: true
