name: Phirepass daemon
description: Phirepass daemon addon for Home Assistant
version: 1.0.5
slug: phirepass-daemon-ha
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
    8080/tcp: 8080
environment:
    PORT: "{{ options.port }}"
schema:
    port: int?
options:
    port: 8080
required:
    - port
host_network: false
host_dbus: true
tmpfs: true
